openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /data/user/{id}:
    get:
      summary: Get User by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /data/product/{id}:
    get:
      summary: Get Product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A Product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
          format: email
          pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - username
        - email
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: double
        quantity:
          type: integer
          format: int64
        description:
          type: invalid
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - name
        - price
        - quantity
