openapi: 3.0.0
info:
  title: Gen API
  description: API for the UI for the open generator
  version: 1.0.0

paths:
  /api/settings:
    get:
      summary: Get settings
      operationId: getSettings
      responses:
        '200':
          description: A JSON object containing application settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings'
    post:
      summary: Update settings
      operationId: updateSettings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings'
      responses:
        '200':
          description: Settings updated successfully
        '400':
          description: Invalid request body

components:
  schemas:
    Settings:
      type: object
      required:
        - urlPrefix
        - fields
      properties:
        urlPrefix:
          type: string
          example: 'https://example.com/api'
        fields:
          type: array
          items:
            $ref: '#/components/schemas/SchemaField'

    # remember - this types are just for what users can put in as metadata values
    SchemaField:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
          example: 'fieldName'
        # isArray:
        #   type: boolean
        #   description: Is the value repeated?
        #   example: false
        type:
          type: string
          # enum: [string, user, id, email, integer, double, price, document, boolean, date, oneOf, anyOf, binary, json, uri]
          enum: [string, integer, double, boolean, oneOf, anyOf]
          example: 'string'
        availableValues:
          type: array
          description: Used for oneOf and anyOf types
          items:
            type: string
          example: ['item1', 'item2']
