dev: install api-gen
	npm run dev
run: 
	npm run dev
build:
	npm run build
install:
	npm i
format:
	npm run format
preview:
	npm run preview
latestNode:
	sudo n latest
	nvm use node
api-gen:
	npm run generate-api
